### ISSUE TITLE
regobs API update

### ISSUE THREAD

**Issue by aaarendt** [communitysnowobs/cso-api#17]
Testing reveals regobs data might not be getting pulled into the CSO database.

* I looked at the [regobs.js](https://github.com/communitysnowobs/cso-api/blob/master/src/import/providers/regobs.js) script to find the API URL we're currently using
* existing link [https://api.nve.no/hydrology/regobs/webapi_latest/search/all](https://api.nve.no/hydrology/regobs/webapi_latest/search/all) throws an error
* I found an API documentation (in Norwegian) and translated it [here](https://translate.google.com/translate?hl=&sl=no&tl=en&u=http%3A%2F%2Fapi.nve.no%2Fdoc%2F)
* which leads us to the [Swagger documentation](https://tst-h-web03.nve.no/regobswebapi/swagger/ui/index)
* from here we should be able to update our script accordingly

**Comment by emiliom** [comment]
Great detective work, @aaarendt . So, the service call we were using no longer works. But the Swagger interface you found might be pointing to an entirely different service / API type. Regardless, regobs ingest does seem to be broken and we'll need to look into this closely. I can ultimately figure out the REST API using the Swagger UI documentation, and can develop Python REST API access examples. But adapting that understanding and code to javascript for the CSO API to work properly may be more difficult, at least for me. If it does get difficult, could we get direct help from Gabe's UAF team, and maybe with some input from Jonah?

**Comment by aaarendt** [comment]
Thanks @emiliom! I haven't spoken with Jonah in quite some time but I expect he'll be available to point us in the right direction. I don't know where things are at with the handoff to UAF.

**Comment by emiliom** [comment]
The regobs importer has been working fine since the migration to UAF. As discussed elsewhere, the error was not with the API call per se. Closing this issue.
